In [16]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [7]:
load_iris()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
print(load_iris()['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [8]:
df = pd.DataFrame(data=load_iris()['data'] , columns=load_iris()['feature_names'])

In [10]:
df['target'] = load_iris()['target']

In [18]:
df['target']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [15]:
df.isna().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [89]:
X_train,X_test,y_train,y_test = train_test_split(df.drop(['target'], axis=1),df['target'] , test_size= 0.3 ,  random_state=42)

In [90]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(105, 4)
(105,)
(45, 4)
(45,)


In [91]:
from sklearn.linear_model import LogisticRegression

In [92]:
Logi_LM_1 = LogisticRegression()

In [93]:
Logi_LM_1.fit(X_train,y_train)

LogisticRegression()

In [94]:
Logi_LM_1.predict_proba(X_test)

array([[4.10205629e-03, 8.12291404e-01, 1.83606540e-01],
       [9.42033890e-01, 5.79655298e-02, 5.80104012e-07],
       [1.58665308e-08, 2.09420285e-03, 9.97905781e-01],
       [6.82522538e-03, 7.73233773e-01, 2.19941002e-01],
       [1.59550199e-03, 7.51298264e-01, 2.47106234e-01],
       [9.50092629e-01, 4.99069118e-02, 4.58695291e-07],
       [7.78045498e-02, 9.04139718e-01, 1.80557322e-02],
       [1.79902131e-04, 1.47492373e-01, 8.52327725e-01],
       [2.42370121e-03, 7.80609289e-01, 2.16967009e-01],
       [2.90088010e-02, 9.40807226e-01, 3.01839733e-02],
       [4.73487641e-04, 2.25322619e-01, 7.74203893e-01],
       [9.62736065e-01, 3.72637511e-02, 1.84138849e-07],
       [9.69205649e-01, 3.07942544e-02, 9.66017432e-08],
       [9.56059250e-01, 4.39404841e-02, 2.65390201e-07],
       [9.76544733e-01, 2.34550773e-02, 1.89584029e-07],
       [4.76687396e-03, 6.63333295e-01, 3.31899831e-01],
       [9.66926040e-06, 2.67292266e-02, 9.73261104e-01],
       [2.76990998e-02, 9.45150

In [95]:
Pred1 = Logi_LM_1.predict(X_test)

In [96]:
Pred1 , y_test.values

(array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
        0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
        0]),
 array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
        0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
        0]))

In [97]:
from sklearn.metrics import f1_score,accuracy_score,confusion_matrix,classification_report

In [98]:
confusion_matrix(y_test,Pred1)

array([[19,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 13]], dtype=int64)

In [99]:
print(classification_report(y_test,Pred1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

